### ISSUE TITLE
Boot Loop Crash

### ISSUE THREAD

**Issue by friedrichweise** [Stunkymonkey/esp8266-smartclock#20]
![image](https://user-images.githubusercontent.com/7392490/37559651-e7753a58-2a29-11e8-891f-3d1b0a9c7fa4.png)

**Comment by Stunkymonkey** [comment]
still not working?

**Comment by friedrichweise** [comment]
Fixed by formatting the file system.

**Comment by friedrichweise** [comment]
linked to https://github.com/esp8266/Arduino/issues/4417
