### ISSUE TITLE
How are we going to handle time zones and summer/wintertime ?

### ISSUE THREAD

**Issue by friedrichweise** [Stunkymonkey/esp8266-smartclock#4]

**Comment by Stunkymonkey** [comment]
very good question...

**Comment by Stunkymonkey** [comment]
f426e70c9c2d15a9bebe2e393310c96f1dc70cf0

**Comment by Stunkymonkey** [comment]
f2471e4e23e755ae376f376f87ec0e4085539f1a
now winter and summertime are updating the time, but the drawing right now is still the old fashioned way
